name: Linux Executable

on:
  push:
    branches: [master]
    tags:
       - 'v*'
  release:
   types: [published]
  workflow_dispatch:

jobs:
  build:
    name: building
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: get QuantLib
      run: |
        git submodule update --init
    - name: Set up Boost
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev libboost-test-dev ninja-build
    - name: cmake configure
      run : mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=false -DBoost_USE_STATIC_LIBS=true -DQL_BUILD_EXAMPLES=false -DQL_BUILD_TEST_SUITE=false -DQL_BUILD_BENCHMARK=false -DQL_ENABLE_SESSIONS=true -DORE_BUILD_DOC=false -G "Ninja" ..
    - name: cmake build
      run: cd build/; pwd; cmake --build . -j $(nproc)
    - name: Save executables as artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v3
      with:
        name: ore-linux
        path: /home/runner/work/Engine/Engine/build/App/ore
    - name: Release executables to tag
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        name: ore-linux
        path: /home/runner/work/Engine/Engine/build/App/ore
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_RELEASE }}
