name: C/C++ MacOS x86

on:
  push:
    branches: [master]
    tags:
       - 'v*'
  release:
   types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: get QuantLib
      run: |
        git submodule update --init
    - name: Install Boost
      run: |
        brew install boost
        cd /usr/local/lib
        ln -s libboost_thread-mt.dylib libboost_thread.dylib
        ln -s libboost_thread-mt.a libboost_thread.a
    - name: cmake configure and build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_OSX_ARCHITECTURES=x86_64 -DORE_USE_ZLIB=ON -DBUILD_SHARED_LIBS=false -DORE_BUILD_DOC=OFF -DORE_BUILD_EXAMPLES=OFF -DORE_BUILD_TESTS=OFF -DORE_BUILD_APP=ON -DQL_BUILD_BENCHMARK=OFF -DQL_BUILD_EXAMPLES=OFF -DQL_BUILD_TEST_SUITE=OFF -DQL_ENABLE_SESSIONS=ON -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -j4
        cmake --install .
    - name: Save executables as artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: ore-macos-x86
        path: /Users/runner/work/Engine/Engine/build/App/ore
    - name: Rename executable to match system
      run: mv "/Users/runner/work/Engine/Engine/build/App/ore" "/Users/runner/work/Engine/Engine/build/App/ore-macos-x86"
    - name: Release executables to tag
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.ref_name }}
        files: /Users/runner/work/Engine/Engine/build/App/ore-macos-x86
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_RELEASE }}