name: C/C++ CI Windows

on:
  workflow_dispatch:

jobs:
  build:
    name: building
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          #- arch: x86
          #  platform: Win32
          #  boost-lib: 32
          - arch: AMD64
            platform: x64
            boost-lib: 64
    steps:
    - uses: actions/checkout@v4
    - name: get QuantLib
      run: |
        git submodule update --init
    - name: Set up Boost
      run: |
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.72.0/binaries/boost_1_72_0-msvc-14.2-${{ matrix.boost-lib }}.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost"
        choco install -y ninja
    - name: cmake configure and build
      env:
        BOOST_ROOT: C:\local\boost
      shell: cmd
      run: |
        mkdir build
        cd build
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Vc\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }} -vcvars_ver=14.3 || exit 1
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DQL_BUILD_EXAMPLES=false -DQL_BUILD_TEST_SUITE=false -DQL_BUILD_BENCHMARK=false -DQL_ENABLE_SESSIONS=true -DORE_BUILD_DOC=false -DORE_BUILD_EXAMPLES=false -DORE_BUILD_APP=true -DORE_BUILD_TESTS=true -DBOOST_INCLUDEDIR=C:\local\boost -DBOOST_LIBRARYDIR=C:\local\boost\lib64-msvc-14.3 -L
        cmake --build . -j 4 --verbose
    - name: Save tests artifacts
      uses: actions/upload-artifact@v4
      if: ${{ matrix.arch == 'AMD64' }}
      with:
        name: test-suites
        path: |
          ${{ github.workspace }}\build\OREData\test\ored-test-suite.exe
          ${{ github.workspace }}\build\OREAnalytics\test\orea-test-suite.exe
          ${{ github.workspace }}\build\QuantExt\test\quantext-test-suite.exe
    - name: Save executables as artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v3
      with:
        name: ore-windows-${{ matrix.arch }}
        path: ${{ github.workspace }}\build\App\ore.exe

  tests:
    name: testing
    runs-on: windows-2022
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: test-suites
          path: ${{ github.workspace }}\test-suites
      - name: run QuantExt tests
        continue-on-error: true
        run: |
          .\test-suites\QuantExt\test\quantext-test-suite.exe
      - name: run OREData tests
        continue-on-error: true
        run: |
          .\test-suites\OREData\test\ored-test-suite.exe -- --base_data_path=.\OREData\test
      #- name: run OREAnalytics tests
      #  continue-on-error: true
      #  run: |
      #    .\test-suites\OREAnalytics\test\orea-test-suite.exe
      - name: Delete test suite artifacts
        if: success() || failure()
        uses: geekyeggo/delete-artifact@v5
        with:
          name: test-suites
          failOnError: false