name: Windows Executable

on: workflow_dispatch

jobs:
  build:
    name: building
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: get QuantLib
      run: |
        git submodule update --init
    - name: Set up Boost
      run: |
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.72.0/binaries/boost_1_72_0-msvc-14.2-64.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost"
        choco install -y ninja
    - name: cmake configure and build
      env:
        BOOST_ROOT: C:\local\boost
      shell: cmd
      run: |
        mkdir build
        cd build
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Vc\Auxiliary\Build\vcvarsall.bat" amd64 -vcvars_ver=14.3 || exit 1
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DQL_BUILD_EXAMPLES=false -DQL_BUILD_TEST_SUITE=false -DQL_BUILD_BENCHMARK=false -DQL_ENABLE_SESSIONS=true -DORE_BUILD_DOC=false -DBOOST_INCLUDEDIR=C:\local\boost -DBOOST_LIBRARYDIR=C:\local\boost\lib64-msvc-14.3 -L
        cmake --build . -j 2 --verbose
        
    - name: Save executables as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ore-exe-windows
        path: D:\a\Engine\Engine\build\App\ore.exe

    - name: Save build directory as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ore_build
        path: D:\a\Engine\Engine\build
    
